"""init

Revision ID: c630ca538299
Revises: 
Create Date: 2025-10-18 01:12:31.951297

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c630ca538299'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_persons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_persons_id'), 'delivery_persons', ['id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('delivery_person_id', sa.Uuid(), nullable=True),
    sa.Column('execution_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'READY_FOR_DELIVERY', 'IN_PROGRESS', 'COMPLETED', name='routestatustype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_person_id'], ['delivery_persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_delivery_person_id'), 'routes', ['delivery_person_id'], unique=False)
    op.create_index(op.f('ix_routes_execution_date'), 'routes', ['execution_date'], unique=False)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_status'), 'routes', ['status'], unique=False)
    op.create_table('packages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=True),
    sa.Column('delivery_order', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(length=6), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'READY_FOR_DELIVERY', 'IN_PROGRESS', 'COMPLETED', name='routestatustype'), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_address', sa.String(length=255), nullable=False),
    sa.Column('geographic_point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_packages_geographic_point', 'packages', ['geographic_point'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_packages_id'), 'packages', ['id'], unique=False)
    op.create_index(op.f('ix_packages_route_id'), 'packages', ['route_id'], unique=False)
    op.create_index(op.f('ix_packages_status'), 'packages', ['status'], unique=False)
    op.create_index(op.f('ix_packages_tracking_number'), 'packages', ['tracking_number'], unique=True)
    op.create_table('package_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('geographic_point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_package_deliveries_geographic_point', 'package_deliveries', ['geographic_point'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_package_deliveries_id'), 'package_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_package_deliveries_package_id'), 'package_deliveries', ['package_id'], unique=False)
    op.create_index(op.f('ix_package_deliveries_route_id'), 'package_deliveries', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_package_deliveries_route_id'), table_name='package_deliveries')
    op.drop_index(op.f('ix_package_deliveries_package_id'), table_name='package_deliveries')
    op.drop_index(op.f('ix_package_deliveries_id'), table_name='package_deliveries')
    op.drop_index('idx_package_deliveries_geographic_point', table_name='package_deliveries', postgresql_using='gist')
    op.drop_table('package_deliveries')
    op.drop_index(op.f('ix_packages_tracking_number'), table_name='packages')
    op.drop_index(op.f('ix_packages_status'), table_name='packages')
    op.drop_index(op.f('ix_packages_route_id'), table_name='packages')
    op.drop_index(op.f('ix_packages_id'), table_name='packages')
    op.drop_index('idx_packages_geographic_point', table_name='packages', postgresql_using='gist')
    op.drop_table('packages')
    op.drop_index(op.f('ix_routes_status'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_execution_date'), table_name='routes')
    op.drop_index(op.f('ix_routes_delivery_person_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_delivery_persons_id'), table_name='delivery_persons')
    op.drop_table('delivery_persons')
    # ### end Alembic commands ###
